# -*- coding: utf-8 -*-
"""GRU_Revenue_Sales.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1gfyFNfOrUXo3VAVPCBFrh3dHLh9Kshmf

Using Tensorflow
"""

import pandas as pd
import kagglehub
import os
from tensorflow.keras.layers import Dense, GRU
from tensorflow.keras.models import Sequential
from tensorflow.keras.optimizers import Adam
from sklearn.preprocessing import MinMaxScaler
import numpy as np

# Download latest version
path = kagglehub.dataset_download("podsyp/time-series-starter-dataset")

print("Path to dataset files:", path)

for file in os.listdir(path):
  print(file)

file_path = os.path.join(path , "Month_Value_1.csv")
df = pd.read_csv(file_path)
df.head()

df.isnull().sum()

df['Sales_quantity'] = df['Sales_quantity'].fillna(df['Sales_quantity'].mean())

df['Average_cost'] = df['Average_cost'].fillna(df['Sales_quantity'] / df['Average_cost'].shape)

total = df['Average_cost'].sum()

df['The_average_annual_payroll_of_the_region'] = df['The_average_annual_payroll_of_the_region'].fillna(total/len(df))

df['Revenue'] = df['Revenue'].fillna(df['Sales_quantity'] / df['Average_cost'])

# date = pd.date_range(start='01.01.2015',end='01.12.2015',freq='D')

scalar_data = MinMaxScaler(feature_range=(0,1))
scaled_data = scalar_data.fit_transform(np.array(df['Sales_quantity']).reshape(-1,1))

def create_dataset(dataset, time_step=1):
  datax , datay = [], []
  for i in range(len(dataset)-time_step-1):
    a = dataset[i:(i+time_step) ,0]
    datax.append(a)
    datay.append(dataset[i+time_step,0])
  return np.array(datax) , np.array(datay)



time_step = 50 # Adjusted time_step to be less than the number of samples (96)
datax, datay = create_dataset(scaled_data, time_step)
datax = datax.reshape(datax.shape[0], datax.shape[1], 1) # Reshape for GRU input (samples, time_steps, features)

model = Sequential()
model.add(GRU(50, return_sequences=True, input_shape=(100,1)))
model.add(GRU(50, return_sequences=True))
model.add(GRU(50))
model.add(Dense(1))
model.compile(optimizer=Adam(learning_rate=0.001),loss='mean_squared_error')

model.fit(datax, datay,epochs=10,batch_size = 32)

input_sequence = scaled_data[-time_step:].reshape(1, time_step, 1)
predicted_values = model.predict(input_sequence)

predicted_values

predicted_values = scalar_data.inverse_transform(predicted_values)
print(
    f"The predicted Quantity of sales  for the next day is: {predicted_values[0][0]:.2f}")

"""Using Torch"""



import torch
import torch.nn as nn
import torch.optim as optim
from torch.utils.data import DataLoader , TensorDataset
from sklearn.model_selection import train_test_split

class Sales_Dataset(torch.utils.data.Dataset):
  def __init__(self,x,y):
    self.x = torch.tensor(x,dtype=torch.float32)
    self.y = torch.tensor(y,dtype=torch.float32)
    self.length = self.x.shape[0]
  def __getitem__(self,idx):
    return self.x[idx], self.y[idx]
  def __len__(self):
    return self.length

train_dataset = Sales_Dataset(datax,datay)
train_loader = DataLoader(train_dataset, batch_size=32, shuffle=True)

class GRU(nn.Module):
  def __init__(self, input_size, hidden_size, num_layers):
    super(GRU, self).__init__()
    self.input_size = input_size
    self.hidden_size = hidden_size
    self.num_layers = num_layers
    self.gru = nn.GRU(input_size, hidden_size, num_layers, batch_first=True)
    self.fc = nn.Linear(hidden_size, 1)
  def forward(self, x):
    h0 = torch.zeros(self.num_layers, x.size(0), self.hidden_size)
    out, _ = self.gru(x, h0)
    out = self.fc(out[:, -1, :])
    return out



model = GRU(input_size=1, hidden_size=50, num_layers=5)
print(model)

epochs = 10
learning_rate = 0.001

for epoch in range(epochs):
  total_epochs = 0
  model.train()
  for feature, label in train_loader:
    # forward pass :
    output = model(feature)
    label = label.view(-1,1)
    # loss :

    loss = loss_fn(output,label)
    # backward pass :
    optimizer.zero_grad()
    loss.backward()
    optimizer.step()

  total_epochs = total_epochs + loss.item()
  avg_loss = total_epochs / len(train_loader)
  print(f" epochs : {epoch+1} Avg loss :{avg_loss}")

model.eval()

